const countries = [
  {
    name: 'Uganda',
    currency: 'UGX',
    prefix: 'UG',
    code: '256',
    language: 'en',
    region: [],
  },
  {
    name: 'Democratic Republic of Congo',
    currency: 'CDF',
    prefix: 'DRC',
    code: '243',
    language: 'fr',
    region: [],
  },
  {
    name: 'Kenya',
    currency: 'KES',
    prefix: 'KE',
    code: '254',
    language: 'en',
    region: [],
  },
  {
    name: 'Rwanda',
    currency: 'RWF',
    prefix: 'RW',
    code: '250',
    language: 'en',
    region: [],
  },
  {
    name: 'Burundi',
    currency: 'BIF',
    prefix: 'BI',
    code: '257',
    language: 'fr',
    region: [],
  },
  {
    name: 'Tanzania',
    currency: 'BIF',
    prefix: 'BI',
    code: '257',
    language: 'en',
    region: [],
  },
  {
    name: 'Ghana',
    currency: 'GHS',
    prefix: 'GH',
    code: '233',
    language: 'en',
    region: [],
  },
  {
    name: 'Nigeria',
    currency: 'NGN',
    prefix: 'NG',
    code: '234',
    language: 'en',
    region: [],
  },
  {
    name: 'Zambia',
    currency: 'ZMW',
    prefix: 'ZM',
    code: '260',
    language: 'en',
    region: [],
  },
  {
    name: 'Senegal',
    currency: 'XOF',
    prefix: 'SN',
    code: '221',
    language: 'fr',
    region: [],
  },
  {
    name: 'Cameroon',
    currency: 'XAF',
    prefix: 'CM',
    code: '237',
    language: 'fr',
    region: [],
  },
  {
    name: 'Ivory Coast',
    currency: 'XOF',
    prefix: 'CV',
    code: '225',
    language: 'fr',
    region: [],
  },
];

export default countries;
